# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Purple\CompetingLayer\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1198, 849)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("network.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Total = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(10)
        self.Total.setFont(font)
        self.Total.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.Total.setObjectName("Total")
        self.Initial_State = QtWidgets.QWidget()
        self.Initial_State.setObjectName("Initial_State")
        self.Initial_Condition = QtWidgets.QGroupBox(self.Initial_State)
        self.Initial_Condition.setGeometry(QtCore.QRect(920, 20, 261, 741))
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Initial_Condition.setFont(font)
        self.Initial_Condition.setStyleSheet("font: 10pt \"Sitka Text\";")
        self.Initial_Condition.setFlat(False)
        self.Initial_Condition.setObjectName("Initial_Condition")
        self.Simulation_Start = QtWidgets.QPushButton(self.Initial_Condition)
        self.Simulation_Start.setGeometry(QtCore.QRect(100, 680, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Simulation_Start.setFont(font)
        self.Simulation_Start.setObjectName("Simulation_Start")
        self.layoutWidget = QtWidgets.QWidget(self.Initial_Condition)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 237, 642))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.Layer_A = QtWidgets.QGroupBox(self.layoutWidget)
        self.Layer_A.setObjectName("Layer_A")
        self.gridLayout = QtWidgets.QGridLayout(self.Layer_A)
        self.gridLayout.setObjectName("gridLayout")
        self.A_node = QtWidgets.QLabel(self.Layer_A)
        self.A_node.setObjectName("A_node")
        self.gridLayout.addWidget(self.A_node, 0, 0, 1, 1)
        self.A_NodeBox = QtWidgets.QComboBox(self.Layer_A)
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.A_NodeBox.setFont(font)
        self.A_NodeBox.setIconSize(QtCore.QSize(12, 12))
        self.A_NodeBox.setObjectName("A_NodeBox")
        self.A_NodeBox.addItem("")
        self.A_NodeBox.addItem("")
        self.gridLayout.addWidget(self.A_NodeBox, 0, 1, 1, 1)
        self.A_internaledge = QtWidgets.QLabel(self.Layer_A)
        self.A_internaledge.setObjectName("A_internaledge")
        self.gridLayout.addWidget(self.A_internaledge, 1, 0, 1, 1)
        self.A_InternalEdgeBox = QtWidgets.QComboBox(self.Layer_A)
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.A_InternalEdgeBox.setFont(font)
        self.A_InternalEdgeBox.setMaxVisibleItems(0)
        self.A_InternalEdgeBox.setIconSize(QtCore.QSize(12, 12))
        self.A_InternalEdgeBox.setObjectName("A_InternalEdgeBox")
        self.A_InternalEdgeBox.addItem("")
        self.A_InternalEdgeBox.addItem("")
        self.gridLayout.addWidget(self.A_InternalEdgeBox, 1, 1, 1, 1)
        self.A_externaledge = QtWidgets.QLabel(self.Layer_A)
        self.A_externaledge.setTextFormat(QtCore.Qt.AutoText)
        self.A_externaledge.setObjectName("A_externaledge")
        self.gridLayout.addWidget(self.A_externaledge, 2, 0, 1, 1)
        self.A_ExternalEdgeBox = QtWidgets.QComboBox(self.Layer_A)
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.A_ExternalEdgeBox.setFont(font)
        self.A_ExternalEdgeBox.setIconSize(QtCore.QSize(12, 12))
        self.A_ExternalEdgeBox.setObjectName("A_ExternalEdgeBox")
        self.A_ExternalEdgeBox.addItem("")
        self.gridLayout.addWidget(self.A_ExternalEdgeBox, 2, 1, 1, 1)
        self.A_structure = QtWidgets.QLabel(self.Layer_A)
        self.A_structure.setObjectName("A_structure")
        self.gridLayout.addWidget(self.A_structure, 3, 0, 1, 1)
        self.A_StructureBox = QtWidgets.QComboBox(self.Layer_A)
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.A_StructureBox.setFont(font)
        self.A_StructureBox.setIconSize(QtCore.QSize(12, 12))
        self.A_StructureBox.setObjectName("A_StructureBox")
        self.A_StructureBox.addItem("")
        self.A_StructureBox.addItem("")
        self.gridLayout.addWidget(self.A_StructureBox, 3, 1, 1, 1)
        self.A_state = QtWidgets.QLabel(self.Layer_A)
        self.A_state.setObjectName("A_state")
        self.gridLayout.addWidget(self.A_state, 4, 0, 1, 1)
        self.A_StateBox = QtWidgets.QComboBox(self.Layer_A)
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.A_StateBox.setFont(font)
        self.A_StateBox.setIconSize(QtCore.QSize(12, 12))
        self.A_StateBox.setObjectName("A_StateBox")
        self.A_StateBox.addItem("")
        self.gridLayout.addWidget(self.A_StateBox, 4, 1, 1, 1)
        self.A_max = QtWidgets.QLabel(self.Layer_A)
        self.A_max.setObjectName("A_max")
        self.gridLayout.addWidget(self.A_max, 5, 0, 1, 1)
        self.A_MAXBox = QtWidgets.QComboBox(self.Layer_A)
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.A_MAXBox.setFont(font)
        self.A_MAXBox.setIconSize(QtCore.QSize(12, 12))
        self.A_MAXBox.setObjectName("A_MAXBox")
        self.A_MAXBox.addItem("")
        self.gridLayout.addWidget(self.A_MAXBox, 5, 1, 1, 1)
        self.A_min = QtWidgets.QLabel(self.Layer_A)
        self.A_min.setObjectName("A_min")
        self.gridLayout.addWidget(self.A_min, 6, 0, 1, 1)
        self.A_MINBox = QtWidgets.QComboBox(self.Layer_A)
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.A_MINBox.setFont(font)
        self.A_MINBox.setIconSize(QtCore.QSize(12, 12))
        self.A_MINBox.setObjectName("A_MINBox")
        self.A_MINBox.addItem("")
        self.gridLayout.addWidget(self.A_MINBox, 6, 1, 1, 1)
        self.gridLayout_4.addWidget(self.Layer_A, 0, 0, 1, 1)
        self.Layer_B = QtWidgets.QGroupBox(self.layoutWidget)
        self.Layer_B.setObjectName("Layer_B")
        self.formLayout = QtWidgets.QFormLayout(self.Layer_B)
        self.formLayout.setObjectName("formLayout")
        self.B_node = QtWidgets.QLabel(self.Layer_B)
        self.B_node.setObjectName("B_node")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.B_node)
        self.B_NodeBox = QtWidgets.QComboBox(self.Layer_B)
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.B_NodeBox.setFont(font)
        self.B_NodeBox.setMaxVisibleItems(0)
        self.B_NodeBox.setIconSize(QtCore.QSize(12, 12))
        self.B_NodeBox.setObjectName("B_NodeBox")
        self.B_NodeBox.addItem("")
        self.B_NodeBox.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.B_NodeBox)
        self.label_11 = QtWidgets.QLabel(self.Layer_B)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.B_InternalEdgeBox = QtWidgets.QComboBox(self.Layer_B)
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.B_InternalEdgeBox.setFont(font)
        self.B_InternalEdgeBox.setIconSize(QtCore.QSize(12, 12))
        self.B_InternalEdgeBox.setObjectName("B_InternalEdgeBox")
        self.B_InternalEdgeBox.addItem("")
        self.B_InternalEdgeBox.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.B_InternalEdgeBox)
        self.label_12 = QtWidgets.QLabel(self.Layer_B)
        self.label_12.setTextFormat(QtCore.Qt.AutoText)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.B_ExternalEdgeBox = QtWidgets.QComboBox(self.Layer_B)
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.B_ExternalEdgeBox.setFont(font)
        self.B_ExternalEdgeBox.setIconSize(QtCore.QSize(12, 12))
        self.B_ExternalEdgeBox.setObjectName("B_ExternalEdgeBox")
        self.B_ExternalEdgeBox.addItem("")
        self.B_ExternalEdgeBox.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.B_ExternalEdgeBox)
        self.label_13 = QtWidgets.QLabel(self.Layer_B)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.B_StructureBox = QtWidgets.QComboBox(self.Layer_B)
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.B_StructureBox.setFont(font)
        self.B_StructureBox.setIconSize(QtCore.QSize(12, 12))
        self.B_StructureBox.setObjectName("B_StructureBox")
        self.B_StructureBox.addItem("")
        self.B_StructureBox.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.B_StructureBox)
        self.label_14 = QtWidgets.QLabel(self.Layer_B)
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.B_StateBox = QtWidgets.QComboBox(self.Layer_B)
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.B_StateBox.setFont(font)
        self.B_StateBox.setIconSize(QtCore.QSize(12, 12))
        self.B_StateBox.setObjectName("B_StateBox")
        self.B_StateBox.addItem("")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.B_StateBox)
        self.gridLayout_4.addWidget(self.Layer_B, 1, 0, 1, 1)
        self.Simulation_Condition = QtWidgets.QGroupBox(self.layoutWidget)
        self.Simulation_Condition.setObjectName("Simulation_Condition")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.Simulation_Condition)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_7 = QtWidgets.QLabel(self.Simulation_Condition)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 0, 1, 1)
        self.StepBox = QtWidgets.QComboBox(self.Simulation_Condition)
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.StepBox.setFont(font)
        self.StepBox.setIconSize(QtCore.QSize(12, 12))
        self.StepBox.setObjectName("StepBox")
        self.StepBox.addItem("")
        self.StepBox.addItem("")
        self.gridLayout_3.addWidget(self.StepBox, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.Simulation_Condition)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 2, 0, 1, 1)
        self.DrawingBox = QtWidgets.QComboBox(self.Simulation_Condition)
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.DrawingBox.setFont(font)
        self.DrawingBox.setIconSize(QtCore.QSize(12, 12))
        self.DrawingBox.setObjectName("DrawingBox")
        self.DrawingBox.addItem("")
        self.DrawingBox.addItem("")
        self.gridLayout_3.addWidget(self.DrawingBox, 2, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.Simulation_Condition)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 6, 0, 1, 1)
        self.DatabaseBox = QtWidgets.QComboBox(self.Simulation_Condition)
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.DatabaseBox.setFont(font)
        self.DatabaseBox.setIconSize(QtCore.QSize(12, 12))
        self.DatabaseBox.setObjectName("DatabaseBox")
        self.DatabaseBox.addItem("")
        self.DatabaseBox.addItem("")
        self.gridLayout_3.addWidget(self.DatabaseBox, 6, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.Simulation_Condition)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 10, 0, 1, 1)
        self.StructuresBox = QtWidgets.QComboBox(self.Simulation_Condition)
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.StructuresBox.setFont(font)
        self.StructuresBox.setIconSize(QtCore.QSize(12, 12))
        self.StructuresBox.setObjectName("StructuresBox")
        self.StructuresBox.addItem("")
        self.StructuresBox.addItem("")
        self.StructuresBox.addItem("")
        self.StructuresBox.addItem("")
        self.gridLayout_3.addWidget(self.StructuresBox, 10, 1, 1, 1)
        self.gridLayout_4.addWidget(self.Simulation_Condition, 2, 0, 1, 1)
        self.condition_settingButton = QtWidgets.QPushButton(self.layoutWidget)
        self.condition_settingButton.setObjectName("condition_settingButton")
        self.gridLayout_4.addWidget(self.condition_settingButton, 3, 0, 1, 1)
        self.Initial_State_Button = QtWidgets.QPushButton(self.Initial_State)
        self.Initial_State_Button.setGeometry(QtCore.QRect(780, 740, 111, 27))
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Initial_State_Button.setFont(font)
        self.Initial_State_Button.setObjectName("Initial_State_Button")
        self.frame = QtWidgets.QFrame(self.Initial_State)
        self.frame.setGeometry(QtCore.QRect(20, 10, 881, 711))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 851, 681))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Total.addTab(self.Initial_State, "")
        self.Total_Result = QtWidgets.QWidget()
        self.Total_Result.setObjectName("Total_Result")
        self.Simulation_Start_2 = QtWidgets.QPushButton(self.Total_Result)
        self.Simulation_Start_2.setGeometry(QtCore.QRect(820, 730, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Simulation_Start_2.setFont(font)
        self.Simulation_Start_2.setObjectName("Simulation_Start_2")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.Total_Result)
        self.graphicsView_2.setGeometry(QtCore.QRect(20, 10, 1101, 711))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.Total.addTab(self.Total_Result, "")
        self.Result_gamma = QtWidgets.QWidget()
        self.Result_gamma.setObjectName("Result_gamma")
        self.buttonBox_4 = QtWidgets.QDialogButtonBox(self.Result_gamma)
        self.buttonBox_4.setGeometry(QtCore.QRect(430, 510, 341, 32))
        self.buttonBox_4.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox_4.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox_4.setObjectName("buttonBox_4")
        self.Total.addTab(self.Result_gamma, "")
        self.Result_beta = QtWidgets.QWidget()
        self.Result_beta.setObjectName("Result_beta")
        self.buttonBox_5 = QtWidgets.QDialogButtonBox(self.Result_beta)
        self.buttonBox_5.setGeometry(QtCore.QRect(420, 520, 341, 32))
        self.buttonBox_5.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox_5.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox_5.setObjectName("buttonBox_5")
        self.Total.addTab(self.Result_beta, "")
        self.Movie = QtWidgets.QWidget()
        self.Movie.setObjectName("Movie")
        self.buttonBox_6 = QtWidgets.QDialogButtonBox(self.Movie)
        self.buttonBox_6.setGeometry(QtCore.QRect(430, 520, 341, 32))
        self.buttonBox_6.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox_6.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox_6.setObjectName("buttonBox_6")
        self.Total.addTab(self.Movie, "")
        self.gridLayout_2.addWidget(self.Total, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.Total.setCurrentIndex(0)
        self.Initial_State_Button.clicked.connect(self.frame.show)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Initial_Condition.setTitle(_translate("MainWindow", "Initial Condition"))
        self.Simulation_Start.setText(_translate("MainWindow", "Simulation Start"))
        self.Layer_A.setTitle(_translate("MainWindow", "Layer A"))
        self.A_node.setText(_translate("MainWindow", "Node"))
        self.A_NodeBox.setItemText(0, _translate("MainWindow", "2048"))
        self.A_NodeBox.setItemText(1, _translate("MainWindow", "128"))
        self.A_internaledge.setText(_translate("MainWindow", "Internal Edge"))
        self.A_InternalEdgeBox.setItemText(0, _translate("MainWindow", "5"))
        self.A_InternalEdgeBox.setItemText(1, _translate("MainWindow", "2"))
        self.A_externaledge.setText(_translate("MainWindow", "External Edge"))
        self.A_ExternalEdgeBox.setItemText(0, _translate("MainWindow", "1"))
        self.A_structure.setText(_translate("MainWindow", "Structure"))
        self.A_StructureBox.setItemText(0, _translate("MainWindow", "1"))
        self.A_StructureBox.setItemText(1, _translate("MainWindow", "2"))
        self.A_state.setText(_translate("MainWindow", "State"))
        self.A_StateBox.setItemText(0, _translate("MainWindow", "[1, 2]"))
        self.A_max.setText(_translate("MainWindow", "MAX"))
        self.A_MAXBox.setItemText(0, _translate("MainWindow", "+2"))
        self.A_min.setText(_translate("MainWindow", "MIN"))
        self.A_MINBox.setItemText(0, _translate("MainWindow", "-2"))
        self.Layer_B.setTitle(_translate("MainWindow", "Layer B"))
        self.B_node.setText(_translate("MainWindow", "Node"))
        self.B_NodeBox.setItemText(0, _translate("MainWindow", "2048"))
        self.B_NodeBox.setItemText(1, _translate("MainWindow", "128"))
        self.label_11.setText(_translate("MainWindow", "Internal Edge"))
        self.B_InternalEdgeBox.setItemText(0, _translate("MainWindow", "5"))
        self.B_InternalEdgeBox.setItemText(1, _translate("MainWindow", "2"))
        self.label_12.setText(_translate("MainWindow", "External Edge"))
        self.B_ExternalEdgeBox.setItemText(0, _translate("MainWindow", "1"))
        self.B_ExternalEdgeBox.setItemText(1, _translate("MainWindow", "16"))
        self.label_13.setText(_translate("MainWindow", "Structure"))
        self.B_StructureBox.setItemText(0, _translate("MainWindow", "1"))
        self.B_StructureBox.setItemText(1, _translate("MainWindow", "2"))
        self.label_14.setText(_translate("MainWindow", "State"))
        self.B_StateBox.setItemText(0, _translate("MainWindow", "[-1]"))
        self.Simulation_Condition.setTitle(_translate("MainWindow", "Simulation Condition"))
        self.label_7.setText(_translate("MainWindow", "Step"))
        self.StepBox.setItemText(0, _translate("MainWindow", "100"))
        self.StepBox.setItemText(1, _translate("MainWindow", "30"))
        self.label_8.setText(_translate("MainWindow", "Drawing"))
        self.DrawingBox.setItemText(0, _translate("MainWindow", "False"))
        self.DrawingBox.setItemText(1, _translate("MainWindow", "True"))
        self.label_9.setText(_translate("MainWindow", "Database"))
        self.DatabaseBox.setItemText(0, _translate("MainWindow", "renew_competition"))
        self.DatabaseBox.setItemText(1, _translate("MainWindow", "competition"))
        self.label_16.setText(_translate("MainWindow", "Structures"))
        self.StructuresBox.setItemText(0, _translate("MainWindow", "RR-RR"))
        self.StructuresBox.setItemText(1, _translate("MainWindow", "BA-BA"))
        self.StructuresBox.setItemText(2, _translate("MainWindow", "RR-BA"))
        self.StructuresBox.setItemText(3, _translate("MainWindow", "BA-RA"))
        self.condition_settingButton.setText(_translate("MainWindow", "Setting"))
        self.Initial_State_Button.setText(_translate("MainWindow", "Initial State"))
        self.Total.setTabText(self.Total.indexOf(self.Initial_State), _translate("MainWindow", "Initial State"))
        self.Simulation_Start_2.setText(_translate("MainWindow", "Simulation Start"))
        self.Total.setTabText(self.Total.indexOf(self.Total_Result), _translate("MainWindow", "Total Result"))
        self.Total.setTabText(self.Total.indexOf(self.Result_gamma), _translate("MainWindow", "Result(gamma)"))
        self.Total.setTabText(self.Total.indexOf(self.Result_beta), _translate("MainWindow", "Result(beta)"))
        self.Total.setTabText(self.Total.indexOf(self.Movie), _translate("MainWindow", "Movie"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

